baseURL = "https://www.nittch.fr/"
theme = "LoveIt"

defaultContentLanguage = "en"
languageCode = "en-us"
languageName = "english"

title = "www.nittch.fr"
subtitle = "Nittch's Blog"
titleSeparator = "-"

enableRobotsTXT = true
enableGitInfo = true

home = [ "HTML", "RSS", "JSON" ]
enableEmoji = true

[author]
  name = "Nicolas TANDÉ"
  email = "nittch@linkea.org"

[menu]
  [[menu.main]]
    weight = 1
    identifier = "Posts"
    name = "Posts"
    url = "/posts/"

  [[menu.main]]
    weight = 2
    identifier = "Categories"
    name = "Categories"
    url = "/categories/"

  [[menu.main]]
    weight = 3
    identifier = "networks"
    name = "My networks"
    url = "/networks/"


[params]
  gitRepo = "https://github.com/nittch/www_nittch_fr"
  dateFormat = "01/02/2006"
  title = "www.nittch.fr"
  description = "Nittch's Blog"

[params.header.title]
  name = "www.nittch.fr"

[params.home.profile]
  title = "Nittch"
  subtitle = "Nicolas TANDÉ"
  typeit = false

[params.social]
  linkedin = "nicolastande"
  github = "nittch"
  thingiverse = "nittch"
  spotify = "nittch"
  lastfm = "nittch"
  discord = "nittch"
  email = "nittch@linkea.org"
  twitter = "nittch"
  rss = "https://www.nittch.fr/index.xml"

