baseURL = "https://www.nittch.fr/"
theme = "LoveIt"

defaultContentLanguage = "en"
languageCode = "en-us"
languageName = "english"

title = "Nittch's projects"
subtitle = "Blog about my hobbies and personnal projects"
titleSeparator = "-"

enableRobotsTXT = true
enableGitInfo = true

home = [ "HTML", "RSS", "JSON" ]
enableEmoji = true

[author]
  name = "Nittch"
  email = "nittch@linkea.org"

[menu]
  [[menu.main]]
    weight = 1
    identifier = "Posts"
    name = "Posts"
    url = "/posts/"

  [[menu.main]]
    weight = 2
    identifier = "Categories"
    name = "Categories"
    url = "/categories/"

  [[menu.main]]
    weight = 3
    identifier = "aboutme"
    name = "About me"
    url = "/aboutme"


[params]
  gitRepo = "https://github.com/nittch/www_nittch_fr"
  dateFormat = "2006-01-02"
  title = "Nittch's projects"
  description = "Blog about my hobbies and personnal projects"

[params.header.title]
  name = "Nittch's projects"

[params.footer]
  hugo = false
  since = 2023

[params.home.profile]
  gravatarEmail = "nittch@linkea.org"
  title = "Nittch<br />Nicolas TANDÉ"
  subtitle = "<p>Virtual Reality: World Hopping, Photography<br />Flight Simulation<br />Senior Software Developer: C++ Expert, Agility</p>More details on <u><a href=/aboutme>About me</a></u> page (contains professional links)"
  disclaimer = "Follow me: <u><a href=https://www.nittch.fr/index.xml target=_blank>RSS</a></u> / <u><a href=https://twitter.com/nittch target=_blank>X(Twitter)</a></u><br />Support me on <u><a href=https://ko-fi.com/nittch target=_blank>Ko-fi</a></u>"
  typeit = false

[params.social]
  linkedin = "nicolastande"
  github = "nittch"
  thingiverse = "nittch"
  instagram = "nittch_wired"
  discord = "nittch"
  email = "nittch@linkea.org"
  twitter = "nittch"
  rss = "https://www.nittch.fr/index.xml"

[params.page.share]
  Twitter = true
  Facebook = false
  Linkedin = true
  Reddit = true
  HackerNews = false
  Line = false
  Weibo = false
